services:
  - type: web
    name: dearfuture
    env: node
    region: oregon
    buildCommand: >
      cd client && 
      rm -rf node_modules package-lock.json && 
      npm install && 
      npm run build &&
      cd ../server && 
      rm -rf node_modules package-lock.json && 
      npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        value: https://dearfuture.onrender.com
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: VERIFIED_SENDER
        sync: false
      - key: PORT
        value: 3000
