services:
  - type: web
    name: dearfuture
    region: oregon
    env: node
    buildCommand: cd client && rm -rf node_modules package-lock.json && npm install --legacy-peer-deps --no-optional && npm run build && cd ../server && npm install --legacy-peer-deps
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        value: https://dearfuture.onrender.com
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: VERIFIED_SENDER
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 20.11.1
